import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { NextThemeProvider } from "@/lib/NextThemeProvider";

const poppins = Poppins({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "ContactHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextThemeProvider>
        {children}
        </NextThemeProvider>
        </body>
    </html>
  );
}
